name: skdownscale
channels:
  - conda-forge
dependencies:
  - pandas
  - xarray
  - seaborn
  - mpl-probscale
  - matplotlib
  - scipy
  - numpy
  - scikit-learn
  - dask
  - distributed
  - pydap
  - docopt
  - zarr
  - pip
  - pip:
      - git+https://github.com/jhamman/scikit-downscale.git
